### ISSUE TITLE
w5500 lib for ESP

### ISSUE THREAD

**Issue by mkeyno** [Wiznet/ioLibrary_Driver#11]
hi, do you have any interested to modified Ethernet (w5500) library to run on the ESP8266 

https://github.com/esp8266/Arduino/commit/2a01c2ad531b2a71983a729a00ca9bf8caa1b3fa

**Comment by irinakim12** [comment]
Maybe, if  SPI pin has it , it is possible for a ethernet to use. Try to test.
Thanks
