### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by fordp2002** [Wiznet/ioLibrary_Driver#15]
This project has a mixture of spaces and tabs for indention an no .editorconfig file. This makes the source code hard to read both in an editor and on the github website.

**Comment by fordp2002** [comment]
I suggest this for the file:
`# editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 3
indent_style = tab
insert_final_newline = true
trim_trailing_whitespace = true`

**Comment by bingdo** [comment]
Thank you for your interest.
I will consider it later.
