### ISSUE TITLE
w550io + nrf51(pca10028) : Network initialization succeeds until first restart of host after it has been freshly flashed(programmed)

### ISSUE THREAD

**Issue by tmtpune** [Wiznet/ioLibrary_Driver#19]
Dear all,
I was trying to add ethernet facility to my nrf51 board. 
The following image should give an idea about the HW connections

![imageedit_7_5302238974](https://user-images.githubusercontent.com/32907605/31834516-cfa1b79c-b5eb-11e7-9c17-bcfa66b6f9b5.jpg)

The network initialization always succeeds in the case of a recently programmed host(nrf51). But when i restart the host, network initialization fails.

But if i reprogram(flash) the host with the same .hex file, network initialization succeds.......what could be the reason
After every reprogramming of the host nrf51,  the network initialization of w550io succeeds

**Comment by tmtpune** [comment]
The following image should give you an idea of the scenario.

![ble_gateway-2](https://user-images.githubusercontent.com/32907605/31831588-a87a26c2-b5e1-11e7-9e3c-4c042b081c5e.jpg)

**Comment by tmtpune** [comment]
The following image should give an idea about the HW connections
![imageedit_7_5302238974](https://user-images.githubusercontent.com/32907605/31832486-d16750ac-b5e4-11e7-9d95-3bd53d8eaa98.jpg)

**Comment by bingdo** [comment]
I recommend you post the content on the forum. [forum.wiznet.io](url)
It will be difficult to hear the answer to your application here.

Thanks.
