### ISSUE TITLE
HTTP POST & Get

### ISSUE THREAD

**Issue by ToasTer86** [Wiznet/ioLibrary_Driver#20]
Dear Wiznet, 

I would like to create a HTTP post & get message to a server.  I am using the Wiznet5100.
How would I start with this using the HTTP library included.

Thanks a lot for any help,

Mark

**Comment by bingdo** [comment]
I recommend you post the content on the forum. [forum.wiznet.io](url)
It will be difficult to hear the answer to your use case here.
Please refer to the following link about HTTP Server application.

STM32F103+W5500
https://github.com/Wiznet/WIZ550web
https://github.com/Wiznet/WIZ550Web_STM32F103RB_CoIDE

Thanks.
