### ISSUE TITLE
Use of Malloc

### ISSUE THREAD

**Issue by lonpalmer** [Wiznet/ioLibrary_Driver#22]
httpServer.c uses Malloc to store strings.  In smaller embedded targets (like AVR), malloc is problematic.  Could we get rid of the malloc in favor of a fixed length string buffer or perhaps allow a #define? 

In httpServer.c line 678.

**Comment by bingdo** [comment]
You can refer to source code of the following link.
[](https://github.com/Wiznet/WIZ550web/tree/master/WIZ550web_Firmware/WIZ550web_HW_Rev1.1/WIZ550web_App/src/Internet/httpServer)

Thanks.

**Comment by bingdo** [comment]
You can refer to source code of the following link.
[WIZ550web](https://github.com/Wiznet/WIZ550web/tree/master/WIZ550web_Firmware/WIZ550web_HW_Rev1.1/WIZ550web_App/src/Internet/httpServer)

Thanks.

**Comment by lonpalmer** [comment]
Sorry, i don't understand your point. The source is still using malloc.

**Comment by bingdo** [comment]
Did you check source codes of http server in WIZ550web_App project?
I think there is no use case of malloc.
If you have more question about http server, please upload your topic in [forum.wiznet.io](https://forum.wiznet.io/) site.

Thanks.

**Comment by lonpalmer** [comment]
Yes, I just confirmed it's still there in this project:

https://github.com/Wiznet/ioLibrary_Driver/blob/master/Internet/httpServer/httpServer.c

Same Line I stated earlier.

Why is the httpServer in this project and in the WIZ550web_App project?

**Comment by bingdo** [comment]
Refer to the following.
[https://github.com/Wiznet/WIZ550web/tree/master/WIZ550web_Firmware/WIZ550web_HW_Rev1.1/WIZ550web_App/src/Internet/httpServer](https://github.com/Wiznet/WIZ550web/tree/master/WIZ550web_Firmware/WIZ550web_HW_Rev1.1/WIZ550web_App/src/Internet/httpServer)

WIZ550web is a http server project.

**Comment by lonpalmer** [comment]
I see. Why does this project also have http server code?

________________________________

**Comment by bingdo** [comment]
If you need more info of WIZ550web, refer to the following.
[http://wizwiki.net/wiki/doku.php?id=products:wiz550web:start](http://wizwiki.net/wiki/doku.php?id=products:wiz550web:start)
Thanks.
