### ISSUE TITLE
This comment doesn't make sense

### ISSUE THREAD

**Issue by jammers-ach** [Wiznet/ioLibrary_Driver#35]
https://github.com/Wiznet/ioLibrary_Driver/blob/4ddea28229c4903de718938327c6b1dd1c79f0d0/Internet/DHCP/dhcp.h#L66

This number can't be modified. It should be fixed. I was just debugging a case where someone had changed that number :)

**Comment by MrEngineer02** [comment]
Apparently at one point the number was up to the vendor, but it has since been standardized.
I agree the comment should be changed.  Perhaps: "DHCP identifier. Do not change."
https://supportforums.cisco.com/t5/lan-switching-and-routing/why-dhcp-option-has-quot-magic-cookie-quot/td-p/1764244

**Comment by khj098765** [comment]
OK I will fix this comment.
thank you for using our product.
