### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by sudhishvln** [Wiznet/ioLibrary_Driver#43]
Hello Sir,

It seems the latest version of Wiznet/ioLibrary_Driver from April 6 2018(W5500_PHY_LINK ) has few bugs in Internet/MQTT.

1. Assignment from incompatible pointer type
I have observed that w5x00_write() from mqtt_interface.c has been declared as having 3 arguments but has been assigned to a pointer mqttwrite with 4 arguments. 
line no 115 mqtt_interface.c:
n->mqttwrite = w5x00_write; 
call from MQTTClient.c line no 36 has 4 arguments
rc = c->ipstack->mqttwrite(c->ipstack, &c->buf[sent], length, TimerLeftMS(timer));

2. same is the case with w5x00_read() from  line no 114 in mqtt_interface.c.
3. line no 165 from mqtt_interface.c
uint8_t myport = 12345;
should have been 
uint16_t myport = 12345;
as "large integer is implicitly truncated to unsigned type"

When possibly can these bugs be fixed.

Can some body provide a temporary fix.

Thanks & Regards,
Sudhish

**Comment by khj098765** [comment]
I will update this bug.
thank you very much
