### ISSUE TITLE
_WIZCHIP_ < W5200 : wizchip_init : Infinite loop when buffer size is set to 0

### ISSUE THREAD

**Issue by vanvught** [Wiznet/ioLibrary_Driver#44]
There are 2 lines with an infinite loop when there is a socket buffer set with zero size.

https://github.com/Wiznet/ioLibrary_Driver/blob/master/Ethernet/wizchip_conf.c#L444
https://github.com/Wiznet/ioLibrary_Driver/blob/master/Ethernet/wizchip_conf.c#L478 

Test case: 
```
#define _WIZCHIP_ 5100
#include "wizchip_conf.h"

uint8_t bufSize[2][4] = { {8,0,0,0},{8,0,0,0}};
wizchip_init(bufSize[0], bufSize[1]);
```

A possible fix can be:
```
while((txsize[i] >> j != 1) && (txsize[i] != 0)){j++;}
while((rxsize[i] >> j != 1) && (rxsize[i] != 0)){j++;}
```

With the above, j=0, therefore 
`setSn_RXBUF_SIZE(i, j);`
will set a zero buffer size for that socket.

- Arjan

**Comment by khj098765** [comment]
Oh! thank you for find bug.
I will fix about this bug.
thank you very much
