### ISSUE TITLE
problem about httpserver 

### ISSUE THREAD

**Issue by nevermorever** [Wiznet/ioLibrary_Driver#50]
Hello,

I am using your httpserver source files,here is some of my code to use the httpserver:

    uint8_t http_server_tx_buf[2048] = {0,},http_server_rx_buf[2048] = {0,},socknumlist[] {SOCK_HTTP_SERVER};
        uint8_t *html = "<html>test</html>";
        uint8_t *name = "index.html";
        reg_httpServer_webContent(name, html);
        httpServer_init(http_server_tx_buf, http_server_rx_buf, 1, socknumlist);

Then i run a httpserver task per second in freeRTOS:

    void http_server_task(void *pvParameters)
    {
        while(1)
        {
            httpServer_run(SOCK_HTTP_SERVER);
            vTaskDelay(1000);
        }
    }

Then i request the webpage via chrome several times:

1 request->	test

2 request->  (blank)

3 request->  (blank)

4 request>-> 狚髌�H唿A驁0

5 request>-> ð?ýôçntp task

6 request>->  øo ý÷ùà

...  only the first time i got a correct response

then i debug the code in send_http_response_body function(start at line 457):

    	if(send_len) send(s, buf, send_len);
    	else flag_datasend_end = 1;
    
    	if(flag_datasend_end)
    	{
    		HTTPSock_Status[get_seqnum].file_start = 0;
    		HTTPSock_Status[get_seqnum].file_len = 0;
    		HTTPSock_Status[get_seqnum].file_offset = 0;
    		flag_datasend_end = 0;
    	}
    	else
    	{
    		HTTPSock_Status[get_seqnum].file_offset += send_len;
    #ifdef _HTTPSERVER_DEBUG_
    		printf("> HTTPSocket[%d] : HTTP Response body - offset [ %ld ]\r\n", s, HTTPSock_Status[get_seqnum].file_offset);
    #endif
    	}

it can never achieve flag_datasend_end =1,so HTTPSock_Status[get_seqnum].file_offset += send_len runs every request, next time i request the webpage,i guess this offsetpoint to a wrong address.so i can't get correct response.

Thank you for your help.

**Comment by khj098765** [comment]
the code in send_http_response_body function(start at line 360):

`	else // remained parts
	{
#ifdef _USE_FLASH_
		if(HTTPSock_Status[get_seqnum]->storage_type == DATAFLASH)
		{
			addr = HTTPSock_Status[get_seqnum].file_start + HTTPSock_Status[get_seqnum].file_offset;
		}
#endif
		send_len = HTTPSock_Status[get_seqnum].file_len - HTTPSock_Status[get_seqnum].file_offset;

		if(send_len > DATA_BUF_SIZE - 1)
		{
			send_len = DATA_BUF_SIZE - 1;
			//HTTPSock_Status[get_seqnum]->file_offset += send_len;
		}
		else
		{
#ifdef _HTTPSERVER_DEBUG_
			printf("> HTTPSocket[%d] : HTTP Response end - file len [ %ld ]byte\r\n", s, HTTPSock_Status[get_seqnum].file_len);
#endif
			// Send process end
			flag_datasend_end = 1;
		}`

If remain data and send_len is larger than DATA_BUF_SIZE, set flag_datasend_end to 1 at this point.
It can achieve flag_datasend_end = 1.
thank you
