### ISSUE TITLE
Missing braces

### ISSUE THREAD

**Issue by newAM** [Wiznet/ioLibrary_Driver#55]
https://github.com/Wiznet/ioLibrary_Driver/blob/15b79ef7c0375d7c698e41cfd2dbe9704a9d68c7/Ethernet/socket.c#L520

Lines 520 and 521 generate a compiler warning for missing braces.  I think the intention was to do the bitwise AND before the logical comparison:

`if((taddr == 0) && ((getSn_MR(sn) & Sn_MR_MACRAW) != Sn_MR_MACRAW)) return SOCKERR_IPINVALID;
   if((port  == 0) && ((getSn_MR(sn) & Sn_MR_MACRAW) != Sn_MR_MACRAW)) return SOCKERR_PORTZERO;`

**Comment by vanvught** [comment]
@khj098765 see also issue #38

**Comment by newAM** [comment]
ah this is a duplicate then, I did not see that one

**Comment by newAM** [comment]
...also did not see that issue had been closed at a glance.  reopening this issue.

**Comment by khj098765** [comment]
Thanks for your advice.
next time If you want fix code you can pull-request.
thank you.
