### ISSUE TITLE
sn范围在(0<=n<=7)

### ISSUE THREAD

**Issue by ZhiFengJia** [Wiznet/ioLibrary_Driver#73]
https://github.com/Wiznet/ioLibrary_Driver/blob/c5be3a85b9799959c87d2e8897682e43c061bbb1/Ethernet/socket.c#L85

**Comment by ZhiFengJia** [comment]
![image](https://user-images.githubusercontent.com/28912477/51017107-bd3e1a00-15ad-11e9-90b3-6de3faea925a.png)

**Comment by irinakim12** [comment]
Hi~ @ZhiFengJia  
The value of _WIZCHIP_SOCK_NUM_  is '8' or '4' in wizchip_conf.h
Therefore, it is correct code.
