### ISSUE TITLE
NibbleToHex() missing in send_DHCP_DISCOVER()

### ISSUE THREAD

**Issue by Fleckz** [Wiznet/ioLibrary_Driver#77]
Just like #23, line 383 in dhcp.c is missing convertion from hex to ascii, shows up in router as weird chars if MAC is not in readable ASCII range!

**Comment by bjnhur** [comment]
Thx a lot~. We'll check your comment and update code.

**Comment by khj098765** [comment]
update done.
@Fleckz  Thank you for your contribute.
