### ISSUE TITLE
setSn_PROTOR(sn, proto) error

### ISSUE THREAD

**Issue by byuljigi** [Wiznet/ioLibrary_Driver#82]
https://github.com/Wiznet/ioLibrary_Driver/blob/40dc8d1f1e747ea19c0972fb26439c5e4287eafc/Ethernet/W5300/w5300.h#L2128

must be changed as following : 
WIZCHIP_WRITE(Sn_PROTOR(sn),(WIZCHIP_READ(Sn_PROTOR(sn)) & 0xFF00) | (((uint16_t)proto) & 0x00FF))

**Comment by irinakim12** [comment]
I checked what you said the part and modified the source code.
I also modified the wronged IR bit in W5300.h

thanks,
BR
irina
