### ISSUE TITLE
NTP_SOCKET is not initialized

### ISSUE THREAD

**Issue by spiralray** [Wiznet/ioLibrary_Driver#9]
Hi,
I found a little problem.

In sntp.c, NTP_SOCKET should be initialized in SNTP_init, but there is no operation.

**Comment by bingdo** [comment]
Hi.

Thank you for your attention.
I will investigate this issue.

**Comment by bingdo** [comment]
Please refer to commit 0cabf53 and NTP example project.
https://github.com/Wiznet/SNTP_LPC11E36_LPCXpresso
